server.port=8084
spring.application.name=analytics-service

spring.datasource.url=jdbc:mysql://localhost:3306/analyticsdb
spring.datasource.username=root
spring.datasource.password=root

kafka.bootstrap-servers=localhost:9092